### ISSUE TITLE
Missing core wordpress files after basic installation

### ISSUE THREAD

**Issue by jacquesletesson** [wesleytodd/YeoPress#147]
Hi guys,

Just to let you know that some core files are missing after installation. All the files listed after *wp-includes* folder are missing. See attached file.

Is it my config or a new bug? 

![fail-install](https://cloud.githubusercontent.com/assets/273400/6896342/928e576c-d6ea-11e4-8d14-17bc3d19aa71.jpg)

**Comment by wesleytodd** [comment]
Yeoman does some caching.  Is it possible that on a previous run it failed to download or extract the tarball?  I believe the files end up in `~/.yeoman`, you can try looking there and removing them, then trying again.  LMK if that worked

**Comment by Dravenrip** [comment]
Hi !

i got exactly the same problem ... but i have no ~/.yeoman file to delete :(
i'm using oh my zsh if it can help.

Thanks !

**Comment by jacquesletesson** [comment]
@Dravenrip Same here, I think it is because we install npm globally...

I'm going to try with a fresh install.

**Comment by Dravenrip** [comment]
ah yes it's possible, i've done it globally too.

**Comment by Toddses** [comment]
Take a look at `~/.cache/yeoman` and see if anything is there. On my machine, that's where the yeoman cache is located.

**Comment by wesleytodd** [comment]
By "globally" you mean `npm install -g generator-wordpress` right?  That shouldn't have an effect.

Since it is more than one person, I am going to guess that it is not a fluke or weird caching flaw.  @Toddses is right on where to check, you should be able to remove everything in that folder.  If that still doesn't work, can you both run with `--verbose` and paste that output here?

**Comment by Dravenrip** [comment]
right Toddess, cache elements were in ~/.cache/yeoman for me. I cleaned this folder and everything goes well.
Thanks for your help.

**Comment by jacquesletesson** [comment]
@Toddses  Thank you! 

@wesleytodd I empty the cache folder. While the installer was fetching the tarball, I got this error : 

´´´/usr/local/lib/node_modules/generator-wordpress/app/index.js:216
			remote.directory('.', this.conf.get('wpDir'));
			      ^
TypeError: Cannot read property 'directory' of undefined
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-wordpress/app/index.js:216:10)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/actions/remote.js:79:21)
    at Stream.<anonymous> (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/actions/fetch.js:70:21)
    at Stream.emit (events.js:129:20)
    at DestroyableTransform.onerror (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/node_modules/stream-combiner/index.js:36:18)
    at DestroyableTransform.emit (events.js:129:20)
    at onwriteError (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)´´´

**Comment by wesleytodd** [comment]
Oh, I think that means the download failed.  We need to get error handling on there.  Creating another ticket for that if anyone wants to claim it!

**Comment by wesleytodd** [comment]
Closing this one in favor of that more explicit issue.
