### ISSUE TITLE
Install #Fail on bad 

### ISSUE THREAD

**Issue by sagevann** [wesleytodd/YeoPress#158]
I can't get yeoWordpress to finish install for me. Bails right after the following:

>> Cannot access database
>> Make sure you create the database and update the credentials in the wp-config.php
>> Starting to install theme

```javascript
     info ... Fetching https://github.com/sageevann/new_winston_wachter/archive/master.tar.gz ...
     info This might take a few moments
./usr/local/lib/node_modules/generator-wordpress/util/wordpress.js:241
			remote.directory('.', path.join(config.contentDir, 'themes', config.themeDi
			      ^
TypeError: Cannot read property 'directory' of undefined
    at /usr/local/lib/node_modules/generator-wordpress/util/wordpress.js:241:10
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/actions/remote.js:81:7)
    at /usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/actions/fetch.js:74:7
    at /usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/index.js:139:4
    at callback (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/node_modules/each-async/index.js:33:4)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/node_modules/each-async/node_modules/onetime/index.js:20:12)
    at emit (events.js:129:20)
    at cb (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/node_modules/got/index.js:69:10)
    at /usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/node_modules/got/index.js:152:6
    at BufferStream.<anonymous> (/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/node_modules/download/node_modules/got/node_modules/read-all-stream/index.js:52:3)
```

**Comment by sagevann** [comment]
I ran twice, bot times it failed. System stats are:

![screen shot 2015-05-14 at 2 05 11 am](https://cloud.githubusercontent.com/assets/157262/7628979/bd48cf76-f9dd-11e4-8025-fea2eade0665.png)

**Comment by sagevann** [comment]
Install flags were as follows ( names of directories etc redacted )

```
? WordPress URL: http://REDACTED:8888
? Table prefix: wp_
? Database host: localhost
? Database name: REDACTED
? Database user: REDACTED
? Database password: REDACTED
? Use Git? Yes
? Would you like to install WordPress as a submodule? No
? Would you like to install WordPress with the custom directory structure? No
? Install a custom theme? Yes
? Destination directory: yeopress
? Theme source type (git/tar) git
? Task runner (grunt/gulp) grunt
? GitHub username: sagevann
? GitHub repository name: REDACTED
? Repository branch: master
? Does this all look correct? Yes

```

**Comment by Toddses** [comment]
This looks a lot like a bug we just fixed. Check your YeoPress version, if you're still on 2.0.0, update to the latest version, 2.0.1. I'm going to close this one, but if updating doesn't fix the issue, let us know and we'll reopen and investigate.
