### ISSUE TITLE
Initial setup not working

### ISSUE THREAD

**Issue by selbekk** [wesleytodd/YeoPress#182]
Hi!

I'm having some trouble getting started.

Ran `sudo npm install -g yo generator-wordpress`, and got this error:

```bash
# Tons of install logs... and then:
npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-wordpress/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-environment/package.json'
npm ERR! code 1
```

When I tried to run `yo wordpress` I got this:

```bash
$ yo wordpress
module.js:339
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/router.js:7:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by apank** [comment]
You need to install the missing module - 

sudo npm install mkdirp
