### ISSUE TITLE
having problems running

### ISSUE THREAD

**Issue by MichaelLSmith** [wesleytodd/YeoPress#183]
When I run yo wordpress I get the following errors:

> > Setting Permissions: 0755 on .
> > events.js:160
> >       throw er; // Unhandled 'error' event
> >       ^

Error: EACCES: permission denied, scandir '.cache/dconf'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.exports.chmodSyncRecursive (/usr/lib/node_modules/generator-wordpress/node_modules/wrench/lib/wrench.js:317:20)
    at Object.exports.chmodSyncRecursive (/usr/lib/node_modules/generator-wordpress/node_modules/wrench/lib/wrench.js:324:21)
    at Object.exports.chmodSyncRecursive (/usr/lib/node_modules/generator-wordpress/node_modules/wrench/lib/wrench.js:324:21)
    at Generator.thisIsSparta (/usr/lib/node_modules/generator-wordpress/app/index.js:310:10)
    at /usr/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/base.js:421:16
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)

any help would be great

**Comment by Toddses** [comment]
Can you run it in verbose mode and copypasta the full rundown? `yo wordpress --verbose`
