### ISSUE TITLE
Error basic setup [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by tiagomatosweb** [wesleytodd/YeoPress#191]
Hi,

Any clue on this error?

>> Setting Permissions: 0755 on .
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.chmod (fs.js:1112:14)
    at Object.exports.chmodSyncRecursive (/usr/local/lib/node_modules/generator-wordpress/node_modules/wrench/lib/wrench.js:327:16)
    at Object.exports.chmodSyncRecursive (/usr/local/lib/node_modules/generator-wordpress/node_modules/wrench/lib/wrench.js:324:21)
    at Generator.thisIsSparta (/usr/local/lib/node_modules/generator-wordpress/app/index.js:310:10)
    at /usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/base.js:421:16
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
Emitted 'error' event at:
    at /usr/local/lib/node_modules/generator-wordpress/node_modules/yeoman-generator/lib/base.js:429:14
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

**Comment by wesleytodd** [comment]
I don't really use or maintain this anymore.  I hope someone else can help.  Maybe it is compatibility with your node version?  I have not seen a report like this before, sorry.

**Comment by tiagomatosweb** [comment]
No worries.
