### ISSUE TITLE
Error on "yo wordpress" command

### ISSUE THREAD

**Issue by kellylawrence** [wesleytodd/YeoPress#25]
<em>EDIT: I'm currently running what appears to be the latest versions of node.js (v0.10.16), NPM (v1.3.8), and Yeoman (v1.0.0), on a Max OS X dev environment for what it's worth.<em>

Upon running the <strong>yo wordpress</strong> command, I receive the following error:

```
TypeError: Cannot redefine property: underline
    at Function.defineProperty (native)
    at addProperty (PATH-TO-MY-FOLDER/node_modules/generator-wordpress/node_modules/prompt/node_modules/winston/node_modules/colors/colors.js:53:12)
    at PATH-TO-MY-FOLDER/node_modules/generator-wordpress/node_modules/prompt/node_modules/winston/node_modules/colors/colors.js:189:3
    at Array.forEach (native)
    at Object.<anonymous> (PATH-TO-MY-FOLDER/node_modules/generator-wordpress/node_modules/prompt/node_modules/winston/node_modules/colors/colors.js:184:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I was able to successfully run the <strong>npm install -g yo generator-wordpress</strong> command to install Yeomans and the WordPress generator, although I did receive the following 5 warnings during the install process:

```
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.16","npm":"1.3.8"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.16","npm":"1.3.8"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.16","npm":"1.3.8"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.16","npm":"1.3.8"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.16","npm":"1.3.8"})
```

Any thoughts on what might be happening here? Please let me know if there's any other additional details I could/should provide!

**Comment by juniorhq88** [comment]
I receive this error:

C:\xampp\htdocs\project\wordpress\wp2>yo wordpress

readline.js:924
            throw err;
            ^

Error: Cannot find module 'download'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Junior Hernadez\AppData\Roaming\npm\node_modules\generator-wordpress\node_modules\yeoman-generator\lib\actions\fetch.js:3:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by wesleytodd** [comment]
@juniorhq88 Looks like a different issue, but looks like the install failed.  Try running `npm cache clean` and re-installing.  good luck!
